spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/Todo
    username: postgres
    password: Admin@123
  redis:
    host: localhost
    port: 6380
  mail:
    host: smtp.gmail.com
    port: 465
    username: alexbanner83@gmail.com
    password: zvhlwzkvcnzzmriu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            protocols: TLSv1.2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9004
